### ISSUE TITLE
"TypeError: this.readFile is not a function" when running with v4.0.2

### ISSUE THREAD

**Issue by onikienko** [webextension-toolbox/webextension-toolbox#489]
## Expected Behavior
Should be able to run extension.

## Current Behavior
When `npm run dev chrome` have error like that:

```
 babel-loader » app\scripts\background.js

webpack-webextension-plugin listens on ws://localhost:35729
TypeError: this.readFile is not a function
    at WebextensionPlugin.addManifest (C:\Projects\experiments\wet-test\node_modules\webpack-webextension-plugin\index.js:192:39)
    at WebextensionPlugin.make (C:\Projects\experiments\wet-test\node_modules\webpack-webextension-plugin\index.js:76:12)
    at Hook.eval
    
    and few more strings
```    

## Steps to Reproduce (for bugs)
1. Bootstrap new extension with [generator-web-extension](https://github.com/webextension-toolbox/generator-web-extension). I selected `Browser` for `Would you like to use UI Action?` question. 
2. After finish run `npm run dev chrome`.
3. You will have an error.

## Context
I have the same issues for all my old extensions created with webextension-toolbox v3.0.0 when update to v4.0.2. All of them were bootstrapped via yo generator (not sure that it's related).

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |   4.0.2      |
| node                    |    14.15.3     |
| OS                      |  Windows 10       |
| browser                 |    Chrome  91.0.4472.124    |
| React    |   17.0.2      |

**Comment by onikienko** [comment]
Just checked with `./examples/bookmark-it` extension from this repo. Have same error here.

**Comment by jcblw** [comment]
Ran into this issue as well. I have not looked too much at why this change was made but once I reverted the change everything worked again.

https://github.com/webextension-toolbox/webpack-webextension-plugin/commit/6693298b01329abc97c255c4ddc73eaa12103af8

v4.0.2 introduced the new version of the `webpack-webextension-plugin` (0.4.0) which contains this commit.

**Comment by balcsida** [comment]
Hi folks,

Thank you so much for reporting this and bearing with this issue - I'll check this on Sunday at earliest.

**Comment by jcblw** [comment]
Coming back to this. Found out lots of my issues had to do with Webpack 4 to 5. I had a version of Webpack 4 pinned in my application.

**Comment by pbek** [comment]
I don't use webpack myself in my project and I have found only webpack 5.40.0 in my lock file.

**Comment by rthaut** [comment]
I just opened #116 to fix this issue. Hopefully it saves you some time, @balcsida.

**Comment by pbek** [comment]
@rthaut, #116, are you sure? That's an issue from 2018.

**Comment by pbek** [comment]
Found it, you mean https://github.com/webextension-toolbox/webpack-webextension-plugin/pull/116, right?
